name: Require Team Review

# Normally, a workflow item like this one shouldn't be necessary, because CODEOWNERS suffices.
# However, CODEOWNERS is unmutably noisy: https://github.com/orgs/community/discussions/35673
# Therefore, this workflow restricts sanctioned PR approvals to a hard-coded list of devs.

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, review_requested, review_request_removed, edited]

jobs:
  check-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check for approval from allowed reviewers
        uses: actions/github-script@v7
        with:
          script: |
            const allowedReviewers = [
              "ihincks",
              "joshuasn",
              "rainerschoe"
            ].map(u => u.toLowerCase());

            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const latestReviews = {};
            for (const r of reviews) {
              latestReviews[r.user.login.toLowerCase()] = r.state;
            }

            const approvedFromAllowed = Object.entries(latestReviews).some(
              ([user, state]) =>
                allowedReviewers.includes(user) && state === "APPROVED"
            );

            if (!approvedFromAllowed) {
              core.setFailed("No approval from an allowed reviewer");
            } else {
              core.info("Approval from allowed reviewer found");
            }
