name: Require Team Review

on:
  pull_request:
    types: [opened, edited, ready_for_review, review_requested, review_request_removed, synchronize]

jobs:
  check-review:
    runs-on: ubuntu-latest
    steps:
      - name: Verify review from team
        uses: actions/github-script@v7
        with:
          script: |
            const teamName = "qiskit-primitives";
            const { data: teamMembers } = await github.rest.teams.listMembersInOrg({
              org: context.repo.owner,
              team_slug: teamName
            });
            const memberLogins = new Set(teamMembers.map(m => m.login.toLowerCase()));

            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const approvedFromTeam = reviews.some(r =>
              r.state === "APPROVED" &&
              memberLogins.has(r.user.login.toLowerCase())
            );

            if (!approvedFromTeam) {
              core.setFailed(`No approval from a member of @${context.repo.owner}/${teamName}`);
            }
